### ISSUE TITLE
Headings in component 

### ISSUE THREAD

**Issue by ashishrawat0** [cybergroupdevs/UniVerseDb#1]
change all vendor and all items change

**Comment by bushrakausar15** [comment]
![image](https://user-images.githubusercontent.com/14238274/75521488-e5950c00-5a2d-11ea-874d-641e9644ee67.png)
![image](https://user-images.githubusercontent.com/14238274/75521514-f0e83780-5a2d-11ea-8ff0-3e8f4920e29c.png)
![image](https://user-images.githubusercontent.com/14238274/75521625-24c35d00-5a2e-11ea-91a7-fc3563df9812.png)
![image](https://user-images.githubusercontent.com/14238274/75521652-30af1f00-5a2e-11ea-9a79-a0bcaf933879.png)
![image](https://user-images.githubusercontent.com/14238274/75521687-43295880-5a2e-11ea-8328-a54bcb206a6b.png)
