### ISSUE TITLE
PO - New PO created with No items selected

### ISSUE THREAD

**Issue by bushrakausar15** [cybergroupdevs/UniVerseDb#19]
PO - New PO created with No items selected
![NewPO with No Items](https://user-images.githubusercontent.com/14238274/75420772-c0859800-595e-11ea-8b72-eb30f933eaf4.png)

**Comment by himanshu1365** [comment]
![Screenshot from 2020-02-28 15-29-55](https://user-images.githubusercontent.com/54837598/75538863-51cc3b80-5a3f-11ea-9aed-054bf50c3e67.png)
